# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('account_manager', models.CharField(blank=True, max_length=30)),
                ('monthly_charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('service_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Leased Line'), (2, 'IBW'), (3, 'Fixed Line')], null=True)),
            ],
        ),
    ]
